### ISSUE TITLE
Licence file

### ISSUE THREAD

**Issue by Flyingmana** [magento-hackathon/Real-Big-Sample-Data#4]
as this project currently draws Interest, could @aepod add a Licence?

**Comment by daim2k5** [comment]
:+1:

**Comment by aepod** [comment]
Hmm, interesting. Whats the best choice for I don't care please use it licensing.

**Comment by paales** [comment]
Since it will be content, CC? If it is software MIT?

**Comment by aepod** [comment]
Added CC for now, if this proceeds into code we can switch over to MIT.
